<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'LosUi\Form\View\Helper\Form'              => __DIR__ . '/src/LosUi/Form/View/Helper/Form.php',
  'LosUi\Form\View\Helper\FormElementErrors' => __DIR__ . '/src/LosUi/Form/View/Helper/FormElementErrors.php',
  'LosUi\Form\View\Helper\FormRow'           => __DIR__ . '/src/LosUi/Form/View/Helper/FormRow.php',
  'LosUi\Module'                             => __DIR__ . '/src/LosUi/Module.php',
  'LosUi\View\Helper\Alert'                  => __DIR__ . '/src/LosUi/View/Helper/Alert.php',
  'LosUi\View\Helper\Badge'                  => __DIR__ . '/src/LosUi/View/Helper/Badge.php',
  'LosUi\View\Helper\FlashMessenger'         => __DIR__ . '/src/LosUi/View/Helper/FlashMessenger.php',
  'LosUi\View\Helper\Icon'                   => __DIR__ . '/src/LosUi/View/Helper/Icon.php',
  'LosUi\View\Helper\Image'                  => __DIR__ . '/src/LosUi/View/Helper/Image.php',
  'LosUi\View\Helper\Label'                  => __DIR__ . '/src/LosUi/View/Helper/Label.php',
  'LosUi\View\Helper\Well'                   => __DIR__ . '/src/LosUi/View/Helper/Well.php',
);
